# Generated by Django 3.0 on 2019-12-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogger',
            name='loggedInBefore',
        ),
        migrations.AddField(
            model_name='blogger',
            name='timeFirstLogin',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
