# Generated by Django 3.0 on 2019-12-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191229_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='description',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogger',
            name='profilepic',
            field=models.ImageField(default='test', upload_to='users/profilepic'),
            preserve_default=False,
        ),
    ]
