# Generated by Django 3.0 on 2019-12-30 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191229_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='displayName',
            field=models.CharField(default='test', max_length=30),
            preserve_default=False,
        ),
    ]
